"""LYGO God-Mode Second Brain — vault on USB mycelium, P0 + Hermes, local-first."""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

from .gatekeeper import P0Gatekeeper
from .hermes_audit import log_event, set_log_path

SIGNATURE = "D9Phi963-GODMODE-BRAIN-v1"

CORE_FILES = ("memory.md", "projects.md", "tasks.md", "notes.md", "personality.md", "LYGO_CONTEXT_RULE.md", "brief.md")
DIRS = ("0-inbox", "1-projects", "2-areas", "3-resources", "4-archive", "raw", "wiki", "lygo")


def resolve_vault_root() -> Path:
    env = os.environ.get("LYGO_BRAIN_VAULT")
    if env:
        return Path(env)
    key = os.environ.get("LYGO_BUILDER_KEY_ROOT")
    if key:
        return Path(key) / "data" / "memory_mycelium" / "vault"
    return Path(__file__).resolve().parents[2] / "data" / "godmode_vault"


def resolve_key_root(vault: Path) -> Path | None:
    key = os.environ.get("LYGO_BUILDER_KEY_ROOT")
    if key:
        return Path(key)
    # vault is .../LYGO_BUILDER_KEY/data/memory_mycelium/vault
    p = vault
    for _ in range(4):
        if (p / "verify_bootstrap.py").is_file():
            return p
        p = p.parent
    return None


def _seed_templates(champion: str = "Lightfather") -> dict[str, str]:
    return {
        "memory.md": "# Memory\n\n- LYGO sovereign operator; USB + Claw + lattice triangle.\n- Anti-drift: master whitepaper on stick and stack.\n",
        "projects.md": "# Projects\n\n## LYGO_Sovereign_Loop (status:: active)\n- Goal: balance Desktop Claw, USB BUILDR, lattice verify\n- Next: run sovereign-loop nightly\n",
        "tasks.md": "# Tasks\n\n- [ ] Run `lygo-claw sovereign-loop` after USB daemon up\n",
        "notes.md": "# Notes (Inbox)\n\n## raw\n- (captures land here)\n\n## to-process\n",
        "personality.md": f"# Personality\n\nYou are **{champion}**. Lead with conclusions. Ground in vault files. Cite paths. Resonance forward.\n",
        "LYGO_CONTEXT_RULE.md": """# LYGO SOVEREIGN CONTEXT RULE

1. Read memory.md and personality.md before answering.
2. Retrieve via tags, [[wiki-links]], projects.md, tasks.md.
3. Cite file paths; if unknown say "Lattice Gaps Detected."
4. All writes pass P0; log via Hermes on stick when available.
""",
        "brief.md": "# Morning Brief\n\n_Generated by LYGO God-Mode loop._\n",
    }


def brain_init(vault: Path | None = None, *, champion: str = "Lightfather") -> dict[str, Any]:
    root = vault or resolve_vault_root()
    root.mkdir(parents=True, exist_ok=True)
    lygo = root / "lygo"
    lygo.mkdir(exist_ok=True)
    created = []
    for name, body in _seed_templates(champion).items():
        p = root / name
        if not p.is_file():
            p.write_text(body, encoding="utf-8")
            created.append(name)
    for d in DIRS:
        (root / d).mkdir(parents=True, exist_ok=True)
    meta = {"signature": SIGNATURE, "vault": str(root), "created": created, "champion": champion}
    (lygo / "brain_manifest.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")
    log_event("godmode_brain_init", detail=meta)
    return {"ok": True, "vault": str(root), "created": created, "signature": SIGNATURE}


def _p0_write(path: Path, text: str, gate: P0Gatekeeper) -> bool:
    v = gate.validate(text)
    if v.get("verdict") == "QUARANTINE":
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def brain_dream(vault: Path | None = None, *, online_gap: bool = False) -> dict[str, Any]:
    root = vault or resolve_vault_root()
    if not (root / "memory.md").is_file():
        brain_init(root)
    key = resolve_key_root(root)
    hermes = (key / "data" / "hermes_audit" / "audit_trail.log") if key else root / "lygo" / "hermes_audit.log"
    set_log_path(hermes)
    gate = P0Gatekeeper()
    actions: list[str] = []

    notes = root / "notes.md"
    if notes.is_file():
        raw = notes.read_text(encoding="utf-8")
        if "## to-process" in raw and len(raw) > 80:
            actions.append("inbox_scan_ok")

    gap_script = None
    if key:
        gap_script = key / "scripts" / "ascension_gap_filler.py"
    if gap_script and gap_script.is_file():
        proc = subprocess.run(
            [sys.executable, str(gap_script)],
            cwd=str(key),
            capture_output=True,
            text=True,
            timeout=120,
            env={**os.environ, "LYGO_BUILDER_KEY_ROOT": str(key)},
        )
        actions.append(f"gap_filler_exit_{proc.returncode}")
    else:
        actions.append("gap_filler_skipped")

    brief = root / "brief.md"
    stamp = time.strftime("%Y-%m-%d %H:%M:%S")
    block = f"\n\n## Loop dream ({stamp})\n- Vault: `{root}`\n- Actions: {', '.join(actions)}\n"
    if brief.is_file():
        _p0_write(brief, brief.read_text(encoding="utf-8") + block, gate)
    log_event("godmode_brain_dream", detail={"actions": actions, "vault": str(root)})
    return {"ok": True, "vault": str(root), "actions": actions, "online_gap": online_gap}


def brain_brief(vault: Path | None = None) -> dict[str, Any]:
    root = vault or resolve_vault_root()
    p = root / "brief.md"
    if not p.is_file():
        return {"ok": False, "error": "no brief.md — run brain-dream first"}
    return {"ok": True, "brief": p.read_text(encoding="utf-8")[-8000:]}


def brain_query(question: str, vault: Path | None = None) -> dict[str, Any]:
    root = vault or resolve_vault_root()
    if not root.is_dir():
        return {"ok": False, "verdict": "Lattice Gaps Detected", "error": "no vault"}
    hits: list[dict[str, str]] = []
    q = question.lower()
    for md in root.rglob("*.md"):
        if md.name.startswith("."):
            continue
        try:
            text = md.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if q in text.lower() or any(w in text.lower() for w in q.split() if len(w) > 4):
            hits.append({"path": str(md.relative_to(root)), "snippet": text[:400]})
    if not hits:
        return {"ok": True, "verdict": "Lattice Gaps Detected", "hits": [], "question": question}
    return {"ok": True, "verdict": "GROUNDED", "hits": hits[:12], "question": question}